[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "HereIsYou"
version = "0.1.1"
description = "BInspected is a Python package for deep runtime introspection of Python objects, exposing constructor signatures, default values, annotations, docstrings, and structural metadata for modules, classes, functions, methods, and properties."
readme = "README.md"
license = { text = "MIT" }
authors = [{ name = "Donald Reilly", email = "donald.reilly.jr@outlook.com" }]
dependencies = []
classifiers = ["Development Status :: 2 - Pre-Alpha"]

[tool.setuptools.packages.find]
where = ["src"]
